[package]
name = "rustup-mirror"
version = "0.4.1"
authors = ["Jiajie Chen <noc@jiegec.ac.cn>"]
edition = "2018"
description = "Setup a local rustup mirror."
repository = "https://github.com/jiegec/rustup-mirror"
readme = "README.md"
keywords = ["rustup", "mirror"]
license = "MIT"

[dependencies]
chrono = "0.4"
clap = "2.32.0"
failure = "0.1.5"
filebuffer = "0.4.0"
glob = "0.3"
indicatif = "0.11.0"
reqwest = { version = "0.10.1", features = ["blocking", "socks"] }
rust-crypto = "0.2.36"
toml = "0.4.10"
url = "1.7.2"