[package]
name = "rustup-mirror"
version = "0.2.0"
authors = ["Jiajie Chen <noc@jiegec.ac.cn>"]
edition = "2018"
description = "Setup a local rustup mirror."
repository = "https://github.com/jiegec/rustup-mirror"
readme = "README.md"
keywords = ["rustup", "mirror"]
license = "MIT"

[dependencies]
reqwest = "0.9.9"
toml = "0.4.10"
url = "1.7.2"
filebuffer = "0.4.0"
rust-crypto = "0.2.36"
clap = "2.32.0"
indicatif = "0.11.0"
